package com.naesan.share.application;

public enum PublicShareErrorCode {
    PUBLIC_SHARE_NOT_FOUND,
    PUBLIC_SHARE_ALREADY_ACTIVE,
    PUBLIC_FILE_EMPTY,
    PUBLIC_FILE_TOO_LARGE,
    PUBLIC_FILE_UNSUPPORTED,
    PUBLIC_FILE_TYPE_MISMATCH,
    PUBLIC_FILE_READ_FAILED
}
